os: linux
dist: bionic
language: shell

_test-common: &_test-common
  language: node_js
  node_js: "lts/*"
  services:
  - redis

_dep-check: &_dep-check
  script:
  - npx -p npm-check-updates ncu -u && npm install
  - npm test
_test: &_test
  script:
  - npm test

_build: &_build
  language: shell
  env: DOCKER_CLI_EXPERIMENTAL=enabled
  addons:
    apt:
      update: true
      sources:
      - sourceline: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
        key_url: https://download.docker.com/linux/ubuntu/gpg
      packages:
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - jq
      - qemu-user
  before_install:
  - sudo mkdir -p /etc/docker
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  before_script:
  - sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - sudo docker run --privileged linuxkit/binfmt:v0.7
  script:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" &> /dev/null
  - export DOCKER_REPO=index.docker.io/${DOCKER_ORG}/${CONTAINER}
  - export DOCKERFILE_PATH=Dockerfile
  - bash .travis/build

stages:
- name: test
  if: (branch = master)
- name: build
  if: (branch = master) AND (type != cron)

jobs:
  include:
  - name: Test
    stage: test
    <<: *_test-common
    <<: *_test
  - name: Update deps and test
    <<: *_test-common
    <<: *_dep-check
  - stage: build
    <<: *_build
