version: '3'

services:
  escapevector:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    privileged: true
#    ports:
#    - "3000:3000"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - "./config:/config"
    environment:
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      PORT: "80"
